name: Pylint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Run pylint and annotate
      continue-on-error: true
      run: |
        pylint $(git ls-files '*.py') --disable=C0114,C0115,C0116 --exit-zero --output-format=parseable > pylint-output.txt

    - name: Annotate pylint results
      if: always()
      run: |
        sed 's/^/::warning file=/' pylint-output.txt | sed 's/:/:line=/' | sed 's/: /,col=/'
